### ISSUE TITLE
请求接口时出现异常请求异常尚未登录

### ISSUE THREAD

**Issue by xiangge332** [yinghualuowu/GenshinDailyHelper.Docs#4]
START RequestId: a1bee772-ce00-4023-b8f8-1a949c42458b

[step 1]初始化，开始加载函数文件 index.sh

成功加载index.sh函数文件

=>完成

[step 2]初始化完成，开始发送ready信号

=>完成

[step 3]开始循环监听处理事件调用

Init Report RequestId: a1bee772-ce00-4023-b8f8-1a949c42458b Coldstart: 316ms (PullCode: 301ms InitRuntime: 4ms InitFunction: 11ms) Memory: 128MB MemUsage: 3.40MB

=>长轮询获取事件

=>监听到事件：{"key1":"test value 1","key2":"test value 2"}

=>调用函数,开始处理事件

进入main_handler

{"key1":"test value 1","key2":"test value 2"}

开始运行GenshinDailyHelper......

[12:59:49]:开始签到

[12:59:49]:开始签到 账号1

[12:59:53]:账号1绑定了1个角色

[12:59:53]:昵称:xiangge,等级:50,区域:天空岛

[12:59:56]:请求接口时出现异常请求异常尚未登录

[12:59:56]:签到结束

函数结束

=>返回 {"key1":"test value 1","key2":"test value 2"}

=>推送函数处理结果

Response RequestId:a1bee772-ce00-4023-b8f8-1a949c42458b RetMsg:{"key1":"test value 1","key2":"test value 2"}

END RequestId:a1bee772-ce00-4023-b8f8-1a949c42458b

Report RequestId:a1bee772-ce00-4023-b8f8-1a949c42458b Duration:7077ms Memory:128MB MemUsage:24.937271MB

**Comment by yinghualuowu** [comment]
cookie不对吧应该。现在readme更新了一条获取cookie的方式

**Comment by xiangge332** [comment]
解决了,谢谢
